name: base_webview
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8

  # State management
  get: ^4.6.6

  # Network connectivity
  connectivity_plus: ^6.0.5

  # WebView functionality
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0

  # URL launcher for opening web links
  url_launcher: ^6.3.1

  # Lottie animations
  lottie: ^3.1.3

  # File picker functionality
  file_picker: ^8.1.2

  # Splash screen setup
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff" # splash screen background color
  image: assets/images/logo.png # specify your logo path

flutter_test:
  sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/images/
    - assets/animation/
  uses-material-design: true
